may:
  #给定一个目录,该目录及子目录下所用的 *.doc 或 *.docx 文件都会被识别并处理
  directory: C:\Users\may\Desktop\新建文件夹
  #是否显示替换过程,可选值:true(显示) | false(不显示).  空默认为false
  showDetail: false
  #被替换字符大小写是否敏感. 可选值: false(不敏感), 被替换字符忽略大小写 may|MAY 都会被替换.  true(敏感,默认), 被替换字符严格区分大小写 may|MAY 不会被同时替换
  caseSensitive: true
  #需要的替换的字符，写在方括号中，注意加上单引号或双引号，避免因特殊字符被过滤，多个字符用逗号隔开。如：['今天','java']  即表示两个需替换的字符
  before: ['今天','java']
  #替换之后的字符，写在方括号中，注意加上单引号或双引号，避免因特殊字符被过滤，多个字符用逗号隔开。如：['明天','go']  注意：替换的字符，顺序要与上面保持一致，即'今天'替换成'明天','java'替换成'go'
  after: ['明天','go']